### ISSUE TITLE
客户端退出会导致服务器崩溃

### ISSUE THREAD

**Issue by qffylqwq** [Welsonpeaches/Python_Chat_Room#1]
Exception in thread Thread-1 (client_thread):
Traceback (most recent call last):
  File "D:\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "D:\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "server.py", line 13, in client_thread
    data = conn.recv(81920)
           ^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

**Comment by Welsonpeaches** [comment]
怎么说呢………………
我服务器端没写好对于客户端退出的代码，先这样吧，你可以尝试套个OpenFRP，网站点这个[OpenFRP](https://console.openfrp.net/)
等我修吧，服务端的1.5.0差不多就可以了
感谢您报的issue

**Comment by Welsonpeaches** [comment]
具体怎么套OpenFRP看Readme底下那个开服教程
